spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/events?currentSchema=event
    driver-class-name: org.postgresql.Driver

server:
  port: 80